config/routes.rb
Rails.application.routes.draw do

  root to: "static_pages#index"
  get 'sobre', to: 'static_pages#sobre'
  get 'contato', to: 'static_pages#contato'
  get 'devolucao', to: 'loans#devolucao'
  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'

  resources :readers
  resources :users, only: [:new,:create,:edit,:update]
  resources :books
  resources :loans

end

app/models/reader.rb
class Reader < ApplicationRecord

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :nome, presence: true, length: { maximum: 50}
  validates :cpf, presence: true, length: { maximum: 14}
  validates :endereco, presence: true, length: { maximum: 50}
  validates :cidade, presence: true, length: { maximum: 40}
  validates :uf, presence: true, length: { maximum: 2}
  validates :email, presence: true, length: { maximum: 255}, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: true }
  validates :telefone, presence: true, length: { maximum: 20}

end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController

  def  index
    if user_signed_in?
      @reader = Reader.all
    else
      flash[:danger] = "Faça Login para continuar"
      redirect_to entrar_path
    end
  end

  def  show
    @reader = Reader.find(params[:id])
  end

  def new
    if user_signed_in?
      @reader = Reader.new
    else
      flash[:danger] = "Faça Login para continuar"
      redirect_to entrar_path
    end
  end

  def create
    @reader = Reader.new(readers_params)
    if @reader.save
      flash[:success] = "Leitor cadastrado com sucesso !"
      redirect_to readers_path
    else
      render 'new'
    end
  end

  def  edit
    @reader = Reader.find(params[:id])
  end

  def  update
    @reader = Reader.find(params[:id])
    if @reader.update(readers_params)
      flash[:success] = "Leitor atualizado com sucesso !"
      redirect_to readers_path
    else
      render 'new'
    end
  end

  def  destroy
    @reader = Reader.find(params[:id])
    @reader.destroy
    redirect_to  readers_path
  end

  private
    def readers_params
      params.require(:reader).permit(:nome,:cpf,:endereco,:cidade,:uf,:email,:telefone)
    end

end

app/helpers/readers_helper.rb
module ReadersHelper
end

app/views/readers/_form.html.erb
<script>

function mascaraMutuario(o, f) {
    v_obj = o;
    v_fun = f;
    setTimeout('execmascara()', 1);
}

function execmascara() {
    v_obj.value = v_fun(v_obj.value);
}

function cpfCnpj(v) {

    //Remove tudo o que não é dígito
    v = v.replace(/\D/g, "");

    if (v.length < 14) { //CPF

        //Coloca um ponto entre o terceiro e o quarto dígitos
        v = v.replace(/(\d{3})(\d)/, "$1.$2");

        //Coloca um ponto entre o terceiro e o quarto dígitos
        //de novo (para o segundo bloco de números)
        v = v.replace(/(\d{3})(\d)/, "$1.$2");

        //Coloca um hífen entre o terceiro e o quarto dígitos
        v = v.replace(/(\d{3})(\d{1,2})$/, "$1-$2");

    } else { //CNPJ

        //Coloca ponto entre o segundo e o terceiro dígitos
        v = v.replace(/^(\d{2})(\d)/, "$1.$2");

        //Coloca ponto entre o quinto e o sexto dígitos
        v = v.replace(/^(\d{2})\.(\d{3})(\d)/, "$1.$2.$3");

        //Coloca uma barra entre o oitavo e o nono dígitos
        v = v.replace(/\.(\d{3})(\d)/, ".$1/$2");

        //Coloca um hífen depois do bloco de quatro dígitos
        v = v.replace(/(\d{4})(\d)/, "$1-$2");

    }

    return v;

}
function mTel(tel) {
    tel = tel.replace(/\D/g, "")
    tel = tel.replace(/^(\d)/, "($1")
    tel = tel.replace(/(.{3})(\d)/, "$1)$2")
    if (tel.length == 9) {
        tel = tel.replace(/(.{1})$/, "-$1")
    } else if (tel.length == 10) {
        tel = tel.replace(/(.{2})$/, "-$1")
    } else if (tel.length == 11) {
        tel = tel.replace(/(.{3})$/, "-$1")
    } else if (tel.length == 12) {
        tel = tel.replace(/(.{4})$/, "-$1")
    } else if (tel.length > 12) {
        tel = tel.replace(/(.{4})$/, "-$1")
    }
    return tel;
}

</script>

<%= form_for @reader do |f| %>
  <%= render 'layouts/error_messages', object: f.object %>
  
  <div class="row">
    <div class="col-md-6"> 
      <div class="form-group">
        <%= f.label :nome %>
        <%= f.text_field :nome, class: 'form-control' , :autocomplete => :off%>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :cpf %>
        <%= f.text_field :cpf, class: 'form-control', :autocomplete => :off,  :onkeypress=>'mascaraMutuario(this, cpfCnpj)', :onblur=>'clearTimeout()', :maxlength=>"14" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6"> 
      <div class="form-group">
        <%= f.label :endereco %>
        <%= f.text_field :endereco, class: 'form-control', :autocomplete => :off %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :cidade %>
        <%= f.text_field :cidade, class: 'form-control' , :autocomplete => :off%>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2"> 
      <div class="form-group">
        <%= f.label :uf %>
        <%= f.text_field :uf, class: 'form-control' , :autocomplete => :off, :maxlength=>"2"%>
      </div>
    </div>
  
    <div class="col-md-5">
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control', :autocomplete => :off %>
      </div>
    </div>

    <div class="col-md-5">
      <div class="form-group">
        <%= f.label :telefone %>
        <%= f.text_field :telefone, class: 'form-control',  :autocomplete => :off, :onkeypress=>'mascaraMutuario(this, mTel)', :maxlength=>"14", :onblur=>'clearTimeout()'  %>
        
      </div>
    </div>
  </div>

  <%= f.submit 'Salvar', class: 'btn btn-block btn-success' %>
<% end %>

app/views/readers/edit.html.erb
<div class="container" style="background: #FFF; border: 1px solid black; padding-bottom: 25px;">
  <div class="col-md-12">
    <h1 class="text-center">Editar Leitor</h1>
  </div>

  <div class="col-md-12">
    
    <%= render 'readers/form' %>

  </div>
</div>

app/views/readers/index.html.erb
<%= provide :titulo , "Leitores" %>
<div  class="table-responsive-md">
    <h2>Leitores </h2>
    <table  class="table table-bordered">
        <thead  class="thead-light">
            <tr>
                <th  scope="col" width="30%">Nome </th >
                <th  scope="col" width="45%">CPF </th >
                <th  scope="col" width="25%" ></th >
            </tr >
        </thead >
        <tbody >
            <% @reader.each do |reader| %>
            <tr>
                <td ><%= reader.nome %></td>
                <td ><%= reader.cpf %></td >
                <td ><%=  link_to 'Detalhes', reader , class: 'btn btn-primary' %>
                <%= link_to  'Editar', edit_reader_path(reader), class: 'btn btn-warning' %>
                <%= link_to  'Excluir', reader , method: :delete ,
                data: { confirm: "Confirma a exclusão do leitor #{reader.nome} ?" }, class: 'btn btn-danger' %></td>
            </tr >
            <% end %>
        </tbody >
    </table >
    <%= link_to  'Novo Leitor', new_reader_url , class: 'btn btn-success' %>
</div >

app/views/readers/new.html.erb
<div class="container" style="background: #FFF; border: 1px solid black; padding-bottom: 25px;">
  <div class="col-xs-12">
    <h1 class="text-center">Cadastrar Leitor</h1>
  </div>

  <div class="col-md-12">

    <%= render 'readers/form' %>

  </div>
</div>

app/views/readers/show.html.erb
<div class="row" style="border: 1px solid black;">
  <div class="col-md-12 col-sm-12" style="padding-bottom: 25px;">
        <h1> Dados do Leitor</h1>
            <br>
            <div class="col-md-6">
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Nome</span>
                    <label type="text" class="form-control" aria-describedby="basic-addon1"><%=  @reader.nome %></label>
                </div>
            </div>
            <div class="col-md-6">
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">CPF</span>
                <label type="text" class="form-control" aria-describedby="basic-addon1"><%=  @reader.cpf %></label>
            </div>
            
            <br>
        </div>
        
        <div class="col-md-6">
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Endereço</span>
                    <label type="text" class="form-control" aria-describedby="basic-addon1"><%=  @reader.endereco %></label>
                </div>
            </div>
            <div class="col-md-6">
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Cidade</span>
                <label type="text" class="form-control" aria-describedby="basic-addon1"><%=  @reader.cidade %></label>
            </div>
            <br>
        </div>

        <div class="col-md-6">
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Estado</span>
                    <label type="text" class="form-control" aria-describedby="basic-addon1"><%=  @reader.uf %></label>
                </div>
            </div>
            <div class="col-md-6">
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Telefone</span>
                <label type="text" class="form-control" aria-describedby="basic-addon1"> <%= @reader.telefone %></label>
            </div>
            <br>
        </div>
        
        <div class="col-md-6">
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">E-mail</span>
                    <label type="text" class="form-control" aria-describedby="basic-addon1"><%=  @reader.email %></label>
                </div>
            </div>
            <div class="col-md-6">
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Atualizado em: </span>
                <label type="text" class="form-control" aria-describedby="basic-addon1"> <%= @reader.updated_at.strftime("%b %d, %Y") %></label>
            </div>
            <br>
        </div>
       
    
    <div  class="text-center">
        <%= link_to  'Voltar', readers_path , class: 'btn btn-primary' %>
        <%= link_to  'Editar', edit_reader_path, class: 'btn btn-warning' %>
        <%= link_to  'Novo Leitor', new_reader_url , class: 'btn btn-success' %>
    </div >


  </div>
</div>