config/routes.rb
Rails.application.routes.draw do

  root to: "static_pages#index"
  get 'sobre', to: 'static_pages#sobre'
  get 'contato', to: 'static_pages#contato'
  get 'devolucao', to: 'loans#devolucao'
  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'

  resources :readers
  resources :users, only: [:new,:create,:edit,:update]
  resources :books
  resources :loans

end

app/models/book.rb
class Book < ApplicationRecord

  validates :titulo, presence: true, length: { maximum: 30}
  validates :autor, presence: true, length: { maximum: 30}
  validates :descricao, presence: true
  validates :edicao, presence: true, length: { maximum: 30}
  validates :editora, presence: true, length: { maximum: 30}
  validates :quantidade, presence: true, numericality: { only_integer: true }

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def  index
    if user_signed_in?
      @book = Book.all
    else
      flash[:danger] = "Faça Login para continuar"
      redirect_to entrar_path
    end
  end

  def  show
    @book = Book.find(params[:id]) 
  end

  def new
    if user_signed_in?
      @book = Book.new
    else
      flash[:danger] = "Faça Login para continuar"
      redirect_to entrar_path
    end
  end

  def create
    @book = Book.new(books_params)
    if @book.save
      flash[:success] = "Livro cadastrado com sucesso !"
      redirect_to books_path
    else
      render 'new'
    end
  end

  def  edit
    @book = Book.find(params[:id])
  end

  def  update
    @book = Book.find(params[:id])
    if @book.update(books_params)
      flash[:success] = "Livro atualizado com sucesso !"
      redirect_to books_path
    else
      render 'new'
    end
  end

  def  destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to  books_path
  end

  private
    def books_params
      params.require(:book).permit(:titulo,:autor,:descricao,:editora,:edicao,:quantidade)
    end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
  <%= render 'layouts/error_messages', object: f.object %>
  <div class="row">
    <div class="col-md-6"> 
      <div class="form-group">
        <%= f.label :titulo %>
        <%= f.text_field :titulo, class: 'form-control col-md-6', :autocomplete => :off %>
      </div>
    </div>

    <div class="col-md-6"> 
      <div class="form-group">
        <%= f.label :autor %>
        <%= f.text_field :autor, class: 'form-control col-md-6', :autocomplete => :off %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6"> 
      <div class="form-group">
        <%= f.label :editora %>
        <%= f.text_field :editora, class: 'form-control', :autocomplete => :off %>
      </div>
    </div>

    <div class="col-md-6"> 
      <div class="form-group">
        <%= f.label :edicao %>
        <%= f.text_field :edicao, class: 'form-control', :autocomplete => :off %>
      </div>
    </div>
  </div>

<div class="row">
  <div class="col-md-6"> 
    <div class="form-group">
      <%= f.label :quantidade %>
      <%= f.number_field :quantidade, class: 'form-control', :autocomplete => :off %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12"> 
    <div class="form-group">
      <%= f.label :descricao %>
      <%= f.text_area :descricao, class: 'form-control', rows: 5 %>
    </div>
  </div>
</div>

  <%= f.submit 'Salvar', class: 'btn btn-success btn-block' %>
<% end %>

app/views/books/edit.html.erb
<div class="container" style="background: #FFF; border: 1px solid black; padding-bottom: 25px;">
  <div class="col-md-12">
    <h1 class="text-center">Editar Livro</h1>
  </div>

  <div class="col-md-12">
    
    <%= render 'books/form' %>

  </div>
</div>

app/views/books/index.html.erb
<%= provide :titulo , "Livros" %>
<div  class="table-responsive-md">
    <h2>Livros </h2>
    <table  class="table table-bordered">
        <thead  class="thead-light">
            <tr>
                <th  scope="col" width="30%">Titulo </th >
                <th  scope="col" width="35%">Autor </th >
                <th  scope="col" width="10%" >Qtd</th >
                <th  scope="col" width="25%" >Ações</th >
            </tr >
        </thead >
        <tbody >
            <% @book.each do |book| %>
            <tr>
                <td ><%= book.titulo %></td>
                <td ><%= book.autor %></td >
                <td ><%= book.quantidade %></td >
                <td><%=  link_to 'Detalhes', book , class: 'btn btn-primary' %>
                <%= link_to  'Editar', edit_book_path(book), class: 'btn btn-warning' %>
                <%= link_to  'Excluir', book , method: :delete ,
                data: { confirm: "Confirma a exclusão do leitor #{book.titulo} ?" }, class: 'btn btn-danger' %></td>
            </tr >
            <% end %>
        </tbody >
    </table >
    <%= link_to  'Novo Livro', new_book_url , class: 'btn btn-success' %>

app/views/books/new.html.erb
<div class="container" style="background: #FFF; border: 1px solid black; padding-bottom: 25px;">

<div class="text-center">
    <h1>Cadastrar Livro</h1>
  </div>

  <div class="col-md-12">

    <%= render 'books/form' %>

  </div>
</div>

app/views/books/show.html.erb
<div class="row" style="border: 1px solid black;">
  <div class="col-md-12 col-sm-12" style="padding-bottom: 25px;">
        <h1> Dados do Livro</h1>
            <br>
            <div class="col-md-6">
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Título</span>
                    <label type="text" class="form-control" aria-describedby="basic-addon1"><%=  @book.titulo %></label>
                </div>
            </div>
            <div class="col-md-6">
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Autor</span>
                <label type="text" class="form-control" aria-describedby="basic-addon1"><%=  @book.autor %></label>
            </div>
            
            <br>
        </div>
        
        <div class="col-md-6">
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Editora</span>
                    <label type="text" class="form-control" aria-describedby="basic-addon1"><%=  @book.editora %></label>
                </div>
            </div>
            <div class="col-md-6">
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Edição</span>
                <label type="text" class="form-control" aria-describedby="basic-addon1"><%=  @book.edicao %></label>
            </div>
            <br>
        </div>
        
        <div class="col-md-6">
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Quantidade</span>
                    <label type="text" class="form-control" aria-describedby="basic-addon1"><%=  @book.quantidade %></label>
                </div>
            </div>
            <div class="col-md-6">
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Atualizado em: </span>
                <label type="text" class="form-control" aria-describedby="basic-addon1"> <%= @book.updated_at.strftime("%b %d, %Y") %></label>
            </div>
            <br>
        </div>
        <div class="col-md-12">
        <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">Descrição</span>
            <textarea type="text" readonly class="form-control" aria-describedby="basic-addon1" style="background-color:white;"><%=  @book.descricao %></textarea>
        </div>
        <br>
    </div>
    
    <div  class="text-center">
        <%= link_to  'Voltar', books_path , class: 'btn btn-primary' %>
        <%= link_to  'Editar', edit_book_path, class: 'btn btn-warning' %>
        <%= link_to  'Novo Livro', new_book_url , class: 'btn btn-success' %>
    </div >


  </div>
</div>