config/routes.rb
Rails.application.routes.draw do

  root to: "static_pages#index"
  get 'sobre', to: 'static_pages#sobre'
  get 'contato', to: 'static_pages#contato'
  get 'devolucao', to: 'loans#devolucao'
  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'

  resources :readers
  resources :users, only: [:new,:create,:edit,:update]
  resources :books
  resources :loans

end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :reader
  belongs_to :book

  validates :reader_id, presence: true
  validates :book_id, presence: true
  validates :data_emprestimo, presence: true
  validates :data_devolucao, presence: true

end

app/controllers/loans_controller.rb
class LoansController < ApplicationController

  def  index
    if user_signed_in?
      @loan = Loan.all
    else
      flash[:danger] = "Faça Login para continuar"
      redirect_to entrar_path
    end
  end

  def new
    if user_signed_in?
      @loan = Loan.new
    else
      flash[:danger] = "Faça Login para continuar"
      redirect_to entrar_path
    end
  end

  def devolucao
    @loan = Loan.find(params[:id])
    @loan.devolvido = true
    @book = Book.find(@loan.book_id)
    @book.quantidade = @book.quantidade + 1
    if @book.save && @loan.save
      flash[:success] = "Emprestimo devolvido com sucesso !"
      redirect_to loans_path
    end
    
  end

  def create
    @loan = Loan.new(loans_params)
    @book = Book.find(@loan.book_id)
    if @book.quantidade > 0 
      @book.quantidade = @book.quantidade - 1
      if @book.save
        if @loan.save
          flash[:success] = "Emprestimo cadastrado com sucesso !"
          redirect_to loans_path
        else
          render 'new'
        end
      end
    else
      flash[:danger] = "Emprestimo não realizado, nenhum exemplar deste livro está disponivel !"
      redirect_to loans_path
    end
  end

  def  edit
    @loan = Loan.find(params[:id])
  end

  def  update
    @loan = Loan.find(params[:id])
    if @loan.update(loans_params)
      flash[:success] = "Emprestimo atualizado com sucesso !"
      redirect_to loans_path
    else
      render 'new'
    end
  end

  def  destroy
    @loan = Loan.find(params[:id])
    @book = Book.find(@loan.book_id)
    @book.quantidade = @book.quantidade + 1
    if @book.save
      @loan.destroy
      redirect_to loans_path
    end
  end

  private
    def loans_params
      params.require(:loan).permit(:reader_id,:book_id,:data_emprestimo,:data_devolucao)
    end

end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/_form.html.erb
<%= form_for @loan do |f| %>
  <%= render 'layouts/error_messages', object: f.object %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :reader_id %>
        <%= collection_select(:loan, :reader_id, Reader.all, :id, :nome, {}, {:class => 'form-control'})%>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :book_id %>
        <%= collection_select(:loan, :book_id, Book.all, :id, :titulo, {}, {:class => 'form-control'})%>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
         <%= f.label :data_emprestimo %>
         <%= f.date_field :data_emprestimo , class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :data_devolucao %>
        <%= f.date_field :data_devolucao, class: 'form-control' %>
      </div>
    </div>
  </div>

  <%= f.submit 'Salvar', class: 'btn btn-success btn-block' %>
<% end %>

app/views/loans/edit.html.erb
<div class="container" style="background: #FFF; border: 1px solid black; padding-bottom: 25px;">
  <div class="col-md-12">
    <h1 class="text-center">Renovar Emprestimo</h1>
  </div>

  <%= form_for @loan do |f| %>
  <%= render 'layouts/error_messages', object: f.object %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :reader_id %>
        <%= collection_select(:loan, :reader_id, Reader.all, :id, :nome, {},  {:class => 'form-control',disabled: true})%>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :book_id %>
        <%= collection_select(:loan, :book_id, Book.all, :id, :titulo, {},  {:class => 'form-control', disabled: true})%>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
         <%= f.label :data_emprestimo %>
         <%= f.date_field :data_emprestimo, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :data_devolucao %>
        <%= f.date_field :data_devolucao, class: 'form-control' %>
      </div>
    </div>
  </div>

  <%= f.submit 'Salvar', class: 'btn btn-success btn-block' %>
<% end %>
</div>

app/views/loans/index.html.erb
<style>
.tamanhoBt{

    size: 40px;

}

</style>

<%= provide :titulo , "Emprestimos" %>
<div  class="table-responsive-md">
    <h2>Emprestimos </h2>
    <table  class="table table-bordered">
        <thead  class="thead-light">
            <tr>
                <th  scope="col" width="25%">Livro </th >
                <th  scope="col" width="20%">Leitor </th >
                <th  scope="col" width="15%">Data de Emprestimo </th >
                <th  scope="col" width="15%">Data de Devolução </th >
                <th  scope="col" width="25%" >Ações</th >
            </tr >
        </thead >
        <tbody >
            <% @loan.each do |loan| %>
                <% if loan.devolvido == false %>
                    <% @book = Book.find(loan.book_id) %>
                    <% @reader = Reader.find(loan.reader_id) %>
                    <tr>
                        <td ><%= @book.titulo %></td>
                        <td ><%= @reader.nome %></td>
                        <td ><%= loan.data_emprestimo.strftime("%d/%m/%Y") %></td>
                        <td ><%= loan.data_devolucao.strftime("%d/%m/%Y")  %></td>
                        <td > <%= link_to  'Renovar', edit_loan_path(loan), class: 'btn btn-warning' %>
                        <%=  link_to 'Devolução', {:controller => 'loans', :action => 'devolucao', id:loan.id },{ class: 'btn btn-primary', data: { confirm: "Confirma a devolução do emprestimo ?" } }%>
                        <%= link_to  'Excluir', loan , method: :delete ,
                        data: { confirm: "Confirma a exclusão do emprestimo ?" }, class: 'btn btn-danger' %></td>
                    </tr >
                <% end %>
            <% end %>
        </tbody >
    </table >
    <%= link_to  'Novo Emprestimo', new_loan_path , class: 'btn btn-success' %>

app/views/loans/new.html.erb
<div class="container" style="background: #FFF; border: 1px solid black; padding-bottom: 25px;">
  <div class="col-md-12">
    <h1 class="text-center">Emprestar Livro</h1>
  </div>

  <div class="col-md-12">

    <%= render 'loans/form' %>

  </div>
</div>