config/routes.rb
Rails.application.routes.draw do

  root to: "static_pages#index"
  get 'sobre', to: 'static_pages#sobre'
  get 'contato', to: 'static_pages#contato'
  get 'devolucao', to: 'loans#devolucao'
  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'

  resources :readers
  resources :users, only: [:new,:create,:edit,:update]
  resources :books
  resources :loans

end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="">
    <div class="alert alert-danger">
      Ops! Encontramos <%= pluralize(object.errors.count, 'erro', 'erros')%>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="rodapeHome">
<footer>
  <small>
    <%= link_to 'Gerenciador Biblioteca. Todos os direitos reservados.', root_path %>
  </small>
  
  <nav>
    <ul>
      <li>
        <%= link_to 'Sobre', sobre_path %>
      </li>
      <li>
        <%= link_to 'Contato', contato_path %>
      </li>
    </ul>
  </nav>
</footer>
</div>

app/views/layouts/_header.html.erb
<style>
.height {
  height:58px;
}
.dropbtn {
  background-color: #222222;
  color: white;
  padding: 16px;
  font-size: 18px;
  border: none;
}
.navbar-brand{
  color:white !important;
  padding: 16px !important;
  font-size: 18px !important;
}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #222222;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: white;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}
.caret {
  color:white;
}

.dropdown-content a:hover {background-color: #0D0D0D;}

.homeMenu a:hover {background-color: #0D0D0D !important; height:58px;

}
.dropdown:hover .dropdown-content {display: block;}

.dropdown:hover .dropbtn {background-color: #222222;}
</style>
<nav class="navbar navbar-inverse navbar-static-top">

  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#expanded-menu" aria-expanded=" false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <% if user_signed_in? %>
    <div class = "homeMenu"> 
        <%= link_to 'Home', root_url, class: 'navbar-brand' %>
      </div>
    <div class="collapse navbar-collapse" id="expanded-menu">
    
      <ul class="nav navbar-nav">
        <div class="dropdown ">
          <button class="dropbtn">Leitores</button><span class="caret"></span></button>
            <div class="dropdown-content">
            <%= link_to 'Cadastrar Leitores', new_reader_path %>
            <%= link_to 'Consultar Leitores', readers_path %>   
            </div>
        </div>
      </ul>

    <ul class="nav navbar-nav">
        <div class="dropdown ">
          <button class="dropbtn">Livros</button><span class="caret"></span></button>
            <div class="dropdown-content">
            <%= link_to 'Cadastrar Livros', new_book_path %>
            <%= link_to 'Consultar Livros', books_path %>   

        </div>
    </div>
    </ul>

    <ul class="nav navbar-nav">
        <div class="dropdown ">
          <button class="dropbtn">Emprestimos</button><span class="caret"></span></button>
            <div class="dropdown-content">
            <%= link_to 'Cadastrar Emprestimos', new_loan_path %>
            <%= link_to 'Consultar Emprestimos', loans_path %>   

        </div>
    </div>
    </ul>
    <% end %>

    <ul class="nav navbar-nav navbar-right">
      <% if !user_signed_in? %>
        <div class = "homeMenu height"> 
          <%= link_to 'Entrar', entrar_path, class: 'navbar-brand' %>
        </div>
      <% else %>
      <div class="dropdown ">
          <button class="dropbtn">Bem Vindo, <%= current_user.name %></button><span class="caret"></span></button>
            <div class="dropdown-content">
            <%= link_to 'Nova Conta', new_user_path %>
            <%= link_to 'Editar', edit_user_path(current_user.id) %>
            <%= link_to 'Sair', sair_path, method: :delete  %>   

      </div>
      <% end %>

    </ul>

    </div>
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GerenciadorBiblioteca</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script>
      function limparAlert() {
        document.getElementById("alert").style.display = "none";
      }
    </script>
    
  </head>

  <body>
    <%= render 'layouts/header' %>
    
    <div class="container">
      <div id="alert">
      <% flash.each do |message_type, message| %>
        <%= content_tag 'div', class: "alert alert-#{message_type} alert-dismissible", role: 'alert' do %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="limparAlert();">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= message %>
        <% end %>
      <% end %>
        </div>
      <%= yield %>

      
      
    </div>
  <div class="container">
  <div class ="rodapeHome">
    <%= render 'layouts/footer' %>
    </div>
  </div>
  </body>
</html>